# Artificial Intelligence - Fall 2024 - Laboratory 02:Python Introduction part II


##### Review

The following formula computes a _Z score_ and measures how far a single raw data value is from the population mean.

\begin{equation*}
z = \frac{X - \mu }{\sigma }
\end{equation*}

where:
* **_X_** is a single raw data value
* `mu` is the population mean
* `sigma` is the population standard deviation

To find the standard deviation, the equation below comes in hand:

\begin{equation*}
\sigma = \sqrt{\frac{\sum \left | X - \mu \right |^{2}}{N}}
\end{equation*}

where **_N_** is the number of data points in the population.

**a.** Using `sum()` and `list comprehension`, compute the mean and the standard deviation for the population defined below:

In [1106]:
data =  [4.5, 5, 5.5, 6, 6.25, 7, 15.25, 18, 18.45, 21, 21.45, 23]
print(data)

[4.5, 5, 5.5, 6, 6.25, 7, 15.25, 18, 18.45, 21, 21.45, 23]


In [1107]:
# Your implementation here:
mean = sum(data) / len(data)
std = (sum([(X-mean)**2 for X in data]) / len(data) )**0.5

print("Mean: ", mean)
print("Standard Deviation: ", std)

Mean:  12.616666666666667
Standard Deviation:  7.167441818544622


**b.** Define the `z_score()` function and implement the mathematical expression. The obtained values should be stored in a _z score_ values list and rounded to 3 decimals.

In [1108]:
# Your implementatio here:
def z_score(data, point):
    mean = sum(data) / len(data)
    std = (sum([(X-mean)**2 for X in data]) / len(data) )**0.5
    
    score = (point - mean) / std

    return score

result = z_score(data = data, point = 5)
print(result)

-1.0626757578917134


**c.** Add the corresponding elongation of each raw data value into a dictionary.

In [1109]:
# Your implementatio here:
def z_score_list(data):
    
    scores = list()

    for i in range(0, len(data)):
        scores.append(z_score(data, data[i]))
    return scores

print(z_score_list(data))
    

[-1.1324356544710383, -1.0626757578917134, -0.9929158613123887, -0.923155964733064, -0.8882760164434017, -0.7836361715744146, 0.36740212198444355, 0.7510815531707296, 0.8138654600921217, 1.169640932646678, 1.2324248395680701, 1.4486805189639769]


## Classes

The object-oriented programming paradigm in Python helps with structuring programs into `individual objects`. But how?

* An Object **O** from a class **C** has a set of properties **_p_** and actions **_a_**.

* The functions of a class are called `methods`. Their responsibility is to model the data corresponding to a given object.

* The objects of a class are known as `instances` and represent the source of collecting data.

```python

class EmptyClas:
    """
    This is a class without variables and methods
    """
    pass # The keyword pass is a placeholder


class MyClass:
    # A class variable
    name = 'My Class'
    
    def my_method(self, my_var):
        # An instance variable
        self.my_instance = my_var
```

In [1110]:
# Implement Task 0 b and c here:

class ScientificConference:
    """
    To define the properties of a class, 
    we use a special method called __init__.
    
    The special variable called "self"
    helps with associating the attributes
    with the new object: similar to `this`
    keyword from other programming languages
    and required to address variables from
    classes. 
    """
    def __init__(self, name, year, papers=None):
        """
        Establish the attributes of the
        class and assign values to the 
        corresponding parameters.
        """ 
        self.name = name
        self.year = year
        """
        b. Add new attribute `papers`
        """
        if papers is None:
            self.papers = dict()
        else:
            self.papers = papers
    
    def add_manuscript(self, title, researcher):
        if researcher not in self.papers:
            self.papers[researcher] = []
        if title not in self.papers[researcher]:
            self.papers[researcher].append(title)

    def __str__(self):
        """
        To return the String representation of
        an object, we use the __str__ method. 
        """
        result = self.name + ' ' + str(self.year) + ': \n'
        for author, papers in self.papers.items():
            result += f'{author}: {", ".join(papers)} \n'
        return result

### Task 0

**a.** Define two new `instances` of the `class ScientificConference` and return their representations.

Your output should look like:

`Proposals for ICML and NeurIPS conferences will be accepted until the end of November 2021.`

_Hint:_ `instance.attribute` helps you extracting a certain property.

In [1111]:
# Your implementation here
conference1 = ScientificConference("AI Tools", 2025)
conference2 = ScientificConference("Healthcare News", 2012)

print("Proposals for {} and {} conferences will be accepted until the end of November 2021".format(conference1.name, conference2.name))


Proposals for AI Tools and Healthcare News conferences will be accepted until the end of November 2021


**b.** Create a new attribute for the `class ScientificConference`, which is a dictionary passed as a parameter to the instances of the class and holds all of the papers of the conference.

_Note:_ You should check if `papers` is `None` in `__init__` and set it to `{}` instead.

_Please handle duplicate entries by removing them!_

**c.** Define the `add_manuscript` method which generates new entries in the dictionary described before. Please consider using the _researcher_ as a `key` and the _title_ as `values`.

In [1112]:
# Verify here if your add_manuscript method works: add an item & print it
print(conference1)
print("----------------------\n")
conference1.add_manuscript(title = "Image Generation AI", researcher="Satoshi")
conference1.add_manuscript(title = "Digital Currencies", researcher="Satoshi")
conference1.add_manuscript(title = "Data Collection", researcher="Google")

print(conference1)

AI Tools 2025: 

----------------------

AI Tools 2025: 
Satoshi: Image Generation AI, Digital Currencies 
Google: Data Collection 



### Task 1

**a.** Define the class `Person` which stores the `title`, `name` and `surname` of a person.

The _tuple_ `allowed_titles` is a class variable which helps to verify if the title of a person is "Mr", "Mrs", "Ms", "Senior Researcher", "Professor of CS" or "Computer Scientist".

An error is returned if the title is not valid.

Use `__str__` defined below:

```python
    def __str__(self):
        return self.title + ' ' + self.surname + ' ' + self.name
```

In [1113]:
class Person:
    def __init__(self, name, surname, title):
        self.title = title
        self.name = name
        self.surname = surname
        self.allowed_titles = ("Mr", "Mrs", "Ms", "Senior Researcher", "Professor of CS", "Computer Scientist")

        if self.title not in self.allowed_titles:
            raise ValueError("The title isn't right")

    def __str__(self):
        return self.title + ' ' + self.surname + ' ' + self.name


**b.** Create two instances of the class Person and verify if the following entries are valid:

* _Mr Ian Goodfellow_,
* _SeniorResearcher Tomas Mikolov._

In [1114]:
# Your implementation here
person = Person(title = "Mr", name = "Ian", surname="Goodfellow")
print(person)

#person2= Person(title = "SeniorResearcher", name = "Tomas", surname = "Mikolov")

Mr Goodfellow Ian


### Task 2

In `ScientificConference` we have been using the paper parameter as a string, but this concept requires a detailed structure.

Introduce a new class, `Paper`, which has the following attributes:

* `authors`, 
* `title`, 
* `a_id`,
* `year`, 
* `status` (published or in development), 
* `peer_rating` (Excellent, Good, Fair, Poor, Barely Acceptable, Unacceptable).

In [1115]:
class Paper:
    def __init__(self, authors, title, a_id, status, year, peer_rating):
        self.authors = authors
        self.title = title
        self.a_id = a_id
        self.status = status
        self.year = year
        self.peer_rating = peer_rating

        valid_status = ["Published", "In Development"]
        valid_rating = ["Excellent", "Good", "Fair", "Poor", "Barely Acceptable", "Unacceptable"]

        if self.status not in valid_status:
            raise ValueError("The status is not valid!")
        
        if self.peer_rating not in valid_rating:
            raise ValueError("The peer rating is not valid")

    def __str__(self):
        return  f'{self.title}, {", ".join([str(author) for author in self.authors])} et al. ({self.year}), a_id: '\
                f'{self.a_id}, status: {self.status}, rating: {self.peer_rating}'

## Inheritence

In Object-Oriented programming, this concept enables us to transfer the methods and the properties of a class to another class.

### Task 3

Create a class named `Researcher`, which inherits the properties and methods from the `Person` class. Besides, this class has an additional parameter, `papers` which is `None` by default.

_Note:_ You should check if `papers` is `None` in `__init__` and set it to `[]` instead.

```python
class Researcher(Person):
    def __init__('Add arguments'):
        super().__init__(title, name, surname)
```

In [1116]:
# Define your first researcher
# Expected output: Senior Researcher Tomas Mikolov

class Researcher(Person):
    def __init__(self, name, surname, title = "Mr", papers = []):
        super().__init__(name, surname, title)
        self.papers = papers if papers is not None else []
        self.co_authored = False

    def verify_co_authorship(self):
        for paper in self.papers:
            if self in paper.authors:
                self.co_authored = True

        return self.co_authored
    
    def add_paper(self, paper):
        self.papers.append(paper)

    def get_papers(self):
        return self.papers

    def get_collab(self, collab_researcher):
        results = []
        
        for paper in self.papers:
            if collab_researcher in paper.authors:
                results.append(paper)

        return results                


### Task 4

Consider the following scientists:

1.  Paper _Deep Learning_ published by Yann LeCun, Yoshua Bengio, Geoffrey Hinton, in _nature 521_, id = https://doi.org/10.1038/nature14539, peer_rating = Excelent.

2. Paper _On the difficulty of training recurrent neural networks_ by Razvan Pascanu, Tomas Mikolov, Professor of computer science Yoshua Bengio, in ICML 2013, id = https://arxiv.org/abs/1211.5063, peer_rating = Excelent.

2. Paper _Generative Adversarial Nets_ by Ian Goodfellow and Yoshua Bengio, NeurIPS 2015, id = http://papers.nips.cc/paper/5423-generative-adversarial-nets.pdf, peer_rating = Excelent.

3. Paper _Handwritten Digit Recognition with a Back-Propagation Network_ by Computer Scientist Yann LeCun, NeurIPS 1989, id =  https://papers.nips.cc/paper/293-handwritten-digit-recognition-with-a-back-propagation-network, peer_rating = Excelent.

4. Paper _Gated Softmax Classification_ by Geoffrey Hintorn, NeurIPS 2010, id = http://papers.neurips.cc/paper/3895-gated-softmax-classification, peer_rating = Good.

_Note:_ Let us consider "Mr" as a default title for the researchers without a specific caption. Also, for the id of a paper, please use only integers from the provided links.

**a.** Define the next 5 scientists and use them in your `paper` objects.

**b.** Create the `verify_co_authorship` function inside the `class Researcher` which checks if a certain researcher ever co-authored a paper.
_Hint:_ Use `self.co_authored = False` inside the `__init__` function.

**c.** Implement the `get_collab` function inside the `class Researcher` to discover the papers written by two researchers.

For instance, if Yoshua Bengio is researcher2 and Ian Goodfellow is researcher3, then:

`print_papers(researcher2.get_collab(researcher3))` should output:

_Generative Adversarial Nets, Mr Ian Goodfellow et al. (2015), a_id: 5423, status: published, rating: Excelent_

_Note:_ This function helps you to print the papers from a given list.

```python
def print_papers(paper_list):
    for paper in paper_list:
        print(paper)
```

**d.** What are the papers written by Yoshua Bengio?

Expected output:

`Deep Learning, Computer Scientist Yann LeCun et al. (2015), a_id: 14539, status: published, rating: Excelent`

`Generative Adversarial Nets, Mr Ian Goodfellow et al. (2015), a_id: 5423, status: published, rating: Excelent`

`Paper On the difficulty of training recurrent neural networks, Mr Razvan Pascanu et al. (2013), a_id: 5063, status: published, rating: Excelent`

**e.** Did he ever co-author a paper?

**f.** Which papers are published by Yann LeCun?

Expected output:

`Deep Learning, Computer Scientist Yann LeCun et al. (2015), a_id: 14539, status: published, rating: Excelent`

`Handwritten Digit Recognition with a Back-Propagation Network, Computer Scientist Yann LeCun et al. (1989), a_id: 293, status: published, rating: Good`

In [1117]:
# a)
researcher1 = Researcher(name = "Yann", surname = "LeCun", title = "Computer Scientist")
researcher2 = Researcher(name = "Yoshua", surname = "Bengio", title = "Professor of CS")
researcher3 = Researcher(name = "Geoffrey", surname = "Hinton")
researcher4 = Researcher(name = "Razvan", surname = "Pascanu")
researcher5 = Researcher(name = "Tomas", surname = "Mikolov")
researcher6 = Researcher(name = "Ian", surname = "Goodfellow")

paper1 = Paper(authors = [researcher1, researcher2, researcher3], title="Deep Learning", a_id=14539, status="Published", peer_rating="Excellent", year=2015)
paper2 = Paper(authors = [researcher4, researcher5], title = "On the difficulty of training recurrent neural networks", a_id = 5063, status = "Published", peer_rating="Excellent", year=2013)
paper3 = Paper(authors = [researcher6, researcher2], title = "Generative Adversarial Nets", a_id = 5423, status = "Published", peer_rating="Excellent", year = 2015)
paper4 = Paper(authors = [researcher1], title = "Handwritten Digit Recognition with a Back-Propagation Network", a_id =  293, status = "Published", peer_rating="Excellent", year = 1989)
paper5 = Paper(authors = [researcher3], title = "Gated Softmax Classification", a_id = 3895, status = "Published", peer_rating="Good", year = 2010)

researcher1.add_paper(paper1)
researcher1.add_paper(paper4)
researcher2.add_paper(paper1)
researcher2.add_paper(paper3)
researcher3.add_paper(paper1)
researcher3.add_paper(paper5)
researcher4.add_paper(paper2)
researcher5.add_paper(paper2)
researcher6.add_paper(paper3)


def print_papers(papers_list):
    for paper in papers_list:
        print(paper)

print(researcher1)
print('\na)-------------\n')
print_papers([paper1, paper2, paper3])
print('\n--------------\n')
print_papers(researcher2.get_collab(researcher1))
print('\n--------------\n')
print_papers(researcher2.papers)
print('\n--------------\n')
print(researcher2.verify_co_authorship())
print('\n--------------\n')
print_papers(researcher1.get_papers())

Computer Scientist LeCun Yann

a)-------------

Deep Learning, Computer Scientist LeCun Yann, Professor of CS Bengio Yoshua, Mr Hinton Geoffrey et al. (2015), a_id: 14539, status: Published, rating: Excellent
On the difficulty of training recurrent neural networks, Mr Pascanu Razvan, Mr Mikolov Tomas et al. (2013), a_id: 5063, status: Published, rating: Excellent
Generative Adversarial Nets, Mr Goodfellow Ian, Professor of CS Bengio Yoshua et al. (2015), a_id: 5423, status: Published, rating: Excellent

--------------

Deep Learning, Computer Scientist LeCun Yann, Professor of CS Bengio Yoshua, Mr Hinton Geoffrey et al. (2015), a_id: 14539, status: Published, rating: Excellent
Handwritten Digit Recognition with a Back-Propagation Network, Computer Scientist LeCun Yann et al. (1989), a_id: 293, status: Published, rating: Excellent
Deep Learning, Computer Scientist LeCun Yann, Professor of CS Bengio Yoshua, Mr Hinton Geoffrey et al. (2015), a_id: 14539, status: Published, rating: Excelle

### Task 5 

Consider an updated version of the `ScientificConference` class, which should have a modified version of the function `add_manuscript`.

Use the `status` and the `peer_rating` variables as a **threshold** to add papers in your `papers` dictionary. The conferences will only be accepting `Excelent` papers. For this case, the dictionary has the year of the paper as `key`, and the `values` are stored as a tuple of `(researcher, manuscript)`. For the papers which don't satisfy this condition, the message _"Please review your submission."_ is displayed.

For papers submitted in 2015, when printing the conference, the `str` function should output:

```
NeurIPS 2020: 
2015: 
Mr Ian Goodfellow: Generative Adversarial Nets, Mr Ian Goodfellow et al. (2015), id: 5423, status: published, rating: Excelent 
Computer Scientist Yann LeCun: Deep Learning, Computer Scientist Yann LeCun et al. (2015), id: 14539, status: published, rating: Excelent
```

In [1118]:
class ScientificConferenceUpdate:
    """
    To define the properties of a class, 
    we use a special method called __init__.
    
    The special variable called "self"
    helps with associating the attributes
    w\ the new object: similar to `this`
    keyword from other programming languages
    and required to address variables from
    classes. 
    """
    def __init__(self, name):
        """
        Establish the attributes of the
        class and assign values to the 
        corresponding parameters.
        """ 
        self.name = name
        self.year = year
        """
        Add new attribute `papers`
        """
    
    def add_manuscript(self, manuscript, researcher):
        'TO DO'
        
    def __str__(self):
        """
        To return the String representation of
        an object, we use the __str__ method. 
        """
        result = self.name + ' ' + str(self.year) + ': \n'
        for year, papers in self.papers.items():
            result += f'{year}: \n'
            for (author, paper) in papers: 
                result += f'{author}: {paper} \n'
        return result

<>:2: SyntaxWarning: invalid escape sequence '\ '
<>:2: SyntaxWarning: invalid escape sequence '\ '
/tmp/ipykernel_53046/4178639201.py:2: SyntaxWarning: invalid escape sequence '\ '
  """
